import {
  FiAlertTriangle,
  FiArrowRight,
  FiArrowLeft,
  FiCheck,
  FiChevronLeft,
  FiChevronRight,
  FiCommand,
  FiCreditCard,
  FiFile,
  FiFileText,
  FiHelpCircle,
  FiImage,
  FiMonitor,
  FiLoader,
  FiMoon,
  FiMoreVertical,
  FiPlus,
  FiSettings,
  FiSun,
  FiTrash2,
  FiTwitter,
  FiUser,
  FiX,
  FiHome,
  FiUsers,
  FiCheckCircle,
  FiClock,
  FiExternalLink,
  FiMessageCircle,
  FiMail,
  FiPhone,
  FiMapPin,
  FiMessageSquare,
  FiShield,
  FiInfo,
  FiGithub,
  FiLinkedin,
  FiUserPlus,
  FiHome as FiBuilding,
} from "react-icons/fi";
import { FaRegUser } from "react-icons/fa";
import { TbBuildingSkyscraper } from "react-icons/tb";
import { LuBriefcaseBusiness } from "react-icons/lu";
import { TbMailCheck } from "react-icons/tb";
import { LuNetwork, LuCloudUpload } from "react-icons/lu";

import type { IconType } from "react-icons";

export type Icon = IconType;

export const Icons = {
  logo: FiCommand,
  close: FiX,
  spinner: FiLoader,
  chevronLeft: FiChevronLeft,
  chevronRight: FiChevronRight,
  trash: FiTrash2,
  settings: FiSettings,
  user: FiUser,
  arrowRight: FiArrowRight,
  arrowLeft: FiArrowLeft,
  help: FiHelpCircle,
  pizza: FiHome,
  sun: FiSun,
  moon: FiMoon,
  laptop: FiMonitor,
  gitHub: FiGithub,
  twitter: FiTwitter,
  check: FiCheck,
  warning: FiAlertTriangle,
  page: FiFile,
  media: FiImage,
  post: FiFileText,
  billing: FiCreditCard,
  ellipsis: FiMoreVertical,
  add: FiPlus,
  github: FiGithub,
  briefcase: LuBriefcaseBusiness,
  users: FiUsers,
  checkCircle: FiCheckCircle,
  clock: FiClock,
  externalLink: FiExternalLink,
  message: FiMessageCircle,
  building: FiHome,
  mail: FiMail,
  phone: FiPhone,
  mapPin: FiMapPin,
  messageSquare: FiMessageSquare,
  shield: FiShield,
  info: FiInfo,
  linkedin: FiLinkedin,
  buildingSkyscraper: TbBuildingSkyscraper,
  userPlus: FiUserPlus,
  userCircle: FaRegUser,
  mailCheck: TbMailCheck,
  network: LuNetwork,
  upload: LuCloudUpload,
};
