import {
  AlertTriangle,
  ArrowRight,
  ArrowLeft,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  ImageIcon,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  BriefcaseBusiness,
  Building,
  Users,
  CheckCircle,
  Clock,
  ExternalLink,
  MessageCircle,
  type LucideIcon,
} from "lucide-react";
import { Github } from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  settings: Settings,
  user: User,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  gitHub: Github,
  twitter: Twitter,
  check: Check,
  warning: AlertTriangle,
  page: File,
  media: ImageIcon,
  post: FileText,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  github: Github,
  briefcase: BriefcaseBusiness,
  users: Users,
  checkCircle: CheckCircle,
  clock: Clock,
  externalLink: ExternalLink,
  message: MessageCircle,
  building: Building,
};
