// ==================== ACTIVITY TYPES ====================

export const ACTIVITY_TYPES = {
  // Authentication
  LOGIN: "LOGIN",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",
  TOKEN_REFRESHED: "TOKEN_REFRESHED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET: "PASSWORD_RESET",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  EMAIL_VERIFIED: "EMAIL_VERIFIED",

  // User Management
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",
  USER_BLOCKED: "USER_BLOCKED",
  USER_UNBLOCKED: "USER_UNBLOCKED",
  ROLE_CHANGED: "ROLE_CHANGED",

  // Invite Management
  INVITE_SENT: "INVITE_SENT",
  INVITE_ACCEPTED: "INVITE_ACCEPTED",
  INVITE_REVOKED: "INVITE_REVOKED",

  // Organization Management
  ORG_CREATED: "ORG_CREATED",
  ORG_UPDATED: "ORG_UPDATED",
  ORG_DELETED: "ORG_DELETED",
  ORG_BLOCKED: "ORG_BLOCKED",
  ORG_UNBLOCKED: "ORG_UNBLOCKED",
  ORG_SETTINGS_CHANGED: "ORG_SETTINGS_CHANGED",

  // Employee Management
  EMPLOYEE_CREATED: "EMPLOYEE_CREATED",
  EMPLOYEE_UPDATED: "EMPLOYEE_UPDATED",
  EMPLOYEE_DELETED: "EMPLOYEE_DELETED",
  EMPLOYEE_INVITED: "EMPLOYEE_INVITED",
  EMPLOYEE_ACTIVATED: "EMPLOYEE_ACTIVATED",
  EMPLOYEE_DEACTIVATED: "EMPLOYEE_DEACTIVATED",

  // Recruiter Management
  RECRUITER_CREATED: "RECRUITER_CREATED",
  RECRUITER_UPDATED: "RECRUITER_UPDATED",
  RECRUITER_DELETED: "RECRUITER_DELETED",
  RECRUITER_ASSIGNED: "RECRUITER_ASSIGNED",
  RECRUITER_REMOVED: "RECRUITER_REMOVED",

  // Job Management
  JOB_CREATED: "JOB_CREATED",
  JOB_UPDATED: "JOB_UPDATED",
  JOB_DELETED: "JOB_DELETED",
  JOB_PUBLISHED: "JOB_PUBLISHED",
  JOB_CLOSED: "JOB_CLOSED",

  // Application Management
  APPLICATION_SUBMITTED: "APPLICATION_SUBMITTED",
  APPLICATION_VIEWED: "APPLICATION_VIEWED",
  APPLICATION_STATUS_CHANGED: "APPLICATION_STATUS_CHANGED",
  APPLICATION_NOTES_ADDED: "APPLICATION_NOTES_ADDED",

  // Referral Management
  REFERRAL_CREATED: "REFERRAL_CREATED",
  REFERRAL_SUBMITTED: "REFERRAL_SUBMITTED",
  REFERRAL_STATUS_CHANGED: "REFERRAL_STATUS_CHANGED",
  REFERRAL_REWARD_EARNED: "REFERRAL_REWARD_EARNED",

  // Session Management
  SESSION_CREATED: "SESSION_CREATED",
  SESSION_REVOKED: "SESSION_REVOKED",
} as const;

export type ActivityType = (typeof ACTIVITY_TYPES)[keyof typeof ACTIVITY_TYPES];
